[target.thumbv7em-none-eabihf]
rustflags = ["-C", "panic=abort", "-C", "link-arg=-nostartfiles"]

[target.thumbv7m-none-eabi]
rustflags = ["-C", "panic=abort", "-C", "link-arg=-nostartfiles"]

[target.thumbv6m-none-eabi]
rustflags = ["-C", "panic=abort", "-C", "link-arg=-nostartfiles"]

[target.aarch64-unknown-none-softfloat]
rustflags = ["-C", "panic=abort"]
